# Generated by Django 2.1.5 on 2019-01-10 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proteins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(max_length=20)),
                ('full_sequence', models.CharField(max_length=9999999)),
                ('membrane_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tmhs_locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmh_start', models.IntegerField()),
                ('tmh_stop', models.IntegerField()),
                ('n_flank_start', models.IntegerField()),
                ('c_flank_end', models.IntegerField()),
                ('n_inside', models.BooleanField()),
                ('n_location', models.CharField(max_length=10)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Proteins')),
            ],
        ),
    ]
