# Generated by Django 2.1.5 on 2019-01-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0002_auto_20190110_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmhs_locations',
            name='tmh_db_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='proteins',
            name='full_sequence',
            field=models.CharField(default=None, max_length=9999999),
        ),
        migrations.AlterField(
            model_name='proteins',
            name='membrane_type',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='proteins',
            name='uniprot_id',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='tmhs_locations',
            name='c_flank_end',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='tmhs_locations',
            name='n_flank_start',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='tmhs_locations',
            name='n_inside',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='tmhs_locations',
            name='n_location',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='tmhs_locations',
            name='tmh_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='tmhs_locations',
            name='tmh_start',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='tmhs_locations',
            name='tmh_stop',
            field=models.IntegerField(default=None),
        ),
    ]
