# Generated by Django 2.1.5 on 2019-01-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0003_auto_20190111_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmhs_locations',
            old_name='protein',
            new_name='protein_uniprot_id',
        ),
    ]
