# Generated by Django 2.1.5 on 2019-01-11 14:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0004_auto_20190111_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='MptopoTmhsLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmh_start', models.IntegerField(default=None)),
                ('tmh_stop', models.IntegerField(default=None)),
                ('n_flank_start', models.IntegerField(default=None)),
                ('c_flank_end', models.IntegerField(default=None)),
                ('n_inside', models.BooleanField(default=None)),
                ('n_location', models.CharField(default='', max_length=10)),
                ('tmh_number', models.IntegerField(default=None)),
                ('structural_segment', models.TextField(default='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(default=None, max_length=20)),
                ('full_sequence', models.TextField()),
                ('membrane_type', models.CharField(default='', max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tmh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmh_db_id', models.IntegerField(unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='TopdbTmhsLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmh_start', models.IntegerField(default=None)),
                ('tmh_stop', models.IntegerField(default=None)),
                ('n_flank_start', models.IntegerField(default=None)),
                ('c_flank_end', models.IntegerField(default=None)),
                ('n_inside', models.BooleanField(default=None)),
                ('n_location', models.CharField(default='', max_length=10)),
                ('tmh_number', models.IntegerField(default=None)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tmh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Tmh')),
            ],
        ),
        migrations.CreateModel(
            name='UniprotTmhsLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmh_start', models.IntegerField(default=None)),
                ('tmh_stop', models.IntegerField(default=None)),
                ('n_flank_start', models.IntegerField(default=None)),
                ('c_flank_end', models.IntegerField(default=None)),
                ('n_inside', models.BooleanField(default=None)),
                ('n_location', models.CharField(default='', max_length=30)),
                ('tmh_number', models.IntegerField(default=None)),
                ('membrane', models.CharField(default='', max_length=30)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tmh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Tmh')),
            ],
        ),
        migrations.RemoveField(
            model_name='tmhs_locations',
            name='protein_uniprot_id',
        ),
        migrations.DeleteModel(
            name='Proteins',
        ),
        migrations.DeleteModel(
            name='Tmhs_locations',
        ),
        migrations.AddField(
            model_name='mptopotmhslocation',
            name='tmh',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Tmh'),
        ),
    ]
