# Generated by Django 2.1.5 on 2019-01-11 15:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0005_auto_20190111_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hydrophobicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyte_average', models.IntegerField(default=None)),
                ('kyte_sliding', models.TextField()),
                ('tmh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Tmh')),
            ],
        ),
        migrations.CreateModel(
            name='OpmTmhsLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmh_start', models.IntegerField(default=None)),
                ('tmh_stop', models.IntegerField(default=None)),
                ('n_flank_start', models.IntegerField(default=None)),
                ('c_flank_end', models.IntegerField(default=None)),
                ('n_inside', models.BooleanField(default=None)),
                ('n_location', models.CharField(default='', max_length=10)),
                ('tmh_number', models.IntegerField(default=None)),
                ('structural_segment', models.TextField(default='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tmh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Tmh')),
            ],
        ),
        migrations.CreateModel(
            name='TmSegmentVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_position', models.IntegerField(default=None)),
                ('original_residue', models.TextField(default='')),
                ('mutant_residue', models.TextField(default='')),
                ('original_source', models.CharField(default='', max_length=50)),
                ('tmh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Tmh')),
            ],
        ),
    ]
