# Generated by Django 2.1.5 on 2019-01-28 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0006_hydrophobicity_opmtmhslocation_tmsegmentvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.IntegerField(unique=True)),
                ('feature_type', models.IntegerField()),
                ('feature_start', models.IntegerField()),
                ('feature_stop', models.IntegerField()),
                ('feature_source_sequence', models.TextField()),
                ('feature_source', models.CharField(default='', max_length=100)),
                ('feature_evidence', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.TextField()),
                ('test_result', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Feature')),
            ],
        ),
        migrations.RemoveField(
            model_name='hydrophobicity',
            name='tmh',
        ),
        migrations.RemoveField(
            model_name='mptopotmhslocation',
            name='tmh',
        ),
        migrations.RemoveField(
            model_name='opmtmhslocation',
            name='tmh',
        ),
        migrations.RemoveField(
            model_name='tmh',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='tmsegmentvariant',
            name='tmh',
        ),
        migrations.RemoveField(
            model_name='topdbtmhslocation',
            name='tmh',
        ),
        migrations.RemoveField(
            model_name='uniprottmhslocation',
            name='tmh',
        ),
        migrations.DeleteModel(
            name='Hydrophobicity',
        ),
        migrations.DeleteModel(
            name='MptopoTmhsLocation',
        ),
        migrations.DeleteModel(
            name='OpmTmhsLocation',
        ),
        migrations.DeleteModel(
            name='Tmh',
        ),
        migrations.DeleteModel(
            name='TmSegmentVariant',
        ),
        migrations.DeleteModel(
            name='TopdbTmhsLocation',
        ),
        migrations.DeleteModel(
            name='UniprotTmhsLocation',
        ),
    ]
