# Generated by Django 2.1.7 on 2019-03-25 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0007_tmh_deltag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tmh_hydrophobicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyte_avg', models.FloatField(default=None)),
                ('ww_avg', models.FloatField(default=None)),
                ('eisenberg_avg', models.FloatField(default=None)),
                ('kyte_window', models.TextField()),
                ('ww_window', models.TextField()),
                ('eisenberg_window', models.TextField()),
                ('tmh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Tmh')),
            ],
        ),
    ]
