# Generated by Django 2.1.5 on 2019-01-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0007_auto_20190128_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_score',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='protein',
            name='uniprot_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
