# Generated by Django 2.1.7 on 2019-02-27 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0009_auto_20190211_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmh',
            old_name='tmh_source_sequence',
            new_name='tmh_sequence',
        ),
        migrations.RemoveField(
            model_name='tmh',
            name='tmh_source',
        ),
        migrations.RemoveField(
            model_name='tmh',
            name='tmh_type',
        ),
    ]
