# Generated by Django 2.1.7 on 2019-03-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0010_auto_20190227_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='membrane_type',
        ),
        migrations.AddField(
            model_name='tmh',
            name='membrane_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variant',
            name='disease_comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='disease_status',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
