# Generated by Django 2.1.7 on 2019-03-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0011_auto_20190320_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmh',
            name='tmh_number',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
