# Generated by Django 2.1.7 on 2019-03-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0013_auto_20190326_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmh_hydrophobicity',
            name='flexibility',
            field=models.TextField(default=''),
        ),
    ]
