# Generated by Django 2.1.7 on 2019-03-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0014_auto_20190326_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmh_hydrophobicity',
            name='flexibility',
        ),
    ]
