# Generated by Django 2.2.2 on 2019-06-28 14:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database_Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.TextField()),
                ('build', models.IntegerField()),
                ('last_run', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_download', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Flank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_or_c', models.CharField(default='', max_length=1, null=True)),
                ('inside_or_outside', models.CharField(default='', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funfam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funfam_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pfam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfam_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(max_length=20, unique=True)),
                ('full_sequence', models.TextField()),
                ('total_tmh_number', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Residue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amino_acid_type', models.CharField(default='', max_length=1)),
                ('sequence_position', models.IntegerField()),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Protein')),
            ],
            options={
                'unique_together': {('protein', 'sequence_position')},
            },
        ),
        migrations.CreateModel(
            name='Tmh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmh_id', models.TextField(unique=True)),
                ('tm_type', models.TextField(default='Unknown')),
                ('tmh_sequence', models.TextField()),
                ('tmh_start', models.IntegerField()),
                ('tmh_stop', models.IntegerField()),
                ('tmh_evidence', models.TextField()),
                ('tmh_number', models.IntegerField()),
                ('tmh_total_number', models.IntegerField(default=None)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('membrane_type', models.CharField(default='', max_length=100)),
                ('n_terminal_inside', models.CharField(default='', max_length=100)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='Uniref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_id', models.CharField(max_length=20, unique=True)),
                ('proteins', models.ManyToManyField(to='tmh_db.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='Tmh_tmsoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.TextField()),
                ('test_result', models.TextField()),
                ('test_score', models.FloatField(default=None)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tmh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Tmh')),
            ],
        ),
        migrations.CreateModel(
            name='Tmh_residue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amino_acid_type', models.CharField(default='', max_length=1)),
                ('amino_acid_location_n_to_c', models.IntegerField()),
                ('amino_acid_location_in_to_out', models.IntegerField(null=True)),
                ('feature_location', models.TextField(default='Unknown')),
                ('evidence', models.TextField()),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Residue')),
                ('tmh_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Tmh')),
            ],
        ),
        migrations.CreateModel(
            name='Tmh_hydrophobicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aromaticity', models.FloatField(default=None)),
                ('flexibility', models.TextField()),
                ('kyte_avg', models.FloatField(default=None)),
                ('ww_avg', models.FloatField(default=None)),
                ('eisenberg_avg', models.FloatField(default=None)),
                ('kyte_window', models.TextField()),
                ('ww_window', models.TextField()),
                ('eisenberg_window', models.TextField()),
                ('tmh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Tmh')),
            ],
        ),
        migrations.CreateModel(
            name='Tmh_deltag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.TextField()),
                ('test_score', models.FloatField(default=None)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tmh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Tmh')),
            ],
        ),
        migrations.CreateModel(
            name='Tail_anchor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence', models.TextField(default='Unknown', null=True)),
                ('protein', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='Subcellular_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(default=None, null=True)),
                ('proteins', models.ManyToManyField(related_name='subcellular_locations', to='tmh_db.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_id', models.CharField(default='', max_length=10)),
                ('uniprot_protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Protein')),
            ],
            options={
                'unique_together': {('pdb_id', 'uniprot_protein')},
            },
        ),
        migrations.CreateModel(
            name='Structural_residue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_position', models.IntegerField()),
                ('pdb_chain', models.CharField(default='', max_length=10)),
                ('author_position', models.IntegerField(null=True)),
                ('structure_aa', models.CharField(default='X', max_length=1, null=True)),
                ('uniprot_position', models.IntegerField()),
                ('memprotmd_headgroups', models.FloatField(null=True)),
                ('memprotmd_tail', models.FloatField(null=True)),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Residue')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Structure')),
            ],
        ),
        migrations.CreateModel(
            name='Phmmer_proteins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_e_value', models.FloatField(null=True)),
                ('domain_e_value', models.FloatField(null=True)),
                ('protein_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein_database_uniprot_id', to='tmh_db.Protein')),
                ('protein_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein_query_uniprot_id', to='tmh_db.Protein')),
            ],
            options={
                'unique_together': {('protein_query', 'protein_database')},
            },
        ),
        migrations.CreateModel(
            name='Pfam_residue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_value', models.FloatField()),
                ('pfam_position', models.IntegerField()),
                ('pfam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Pfam')),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Residue')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(unique=True)),
                ('proteins', models.ManyToManyField(related_name='keywords', to='tmh_db.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='Go',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go_id', models.CharField(max_length=20, unique=True)),
                ('proteins', models.ManyToManyField(related_name='gos', to='tmh_db.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='Funfamstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_key', models.TextField(default='NA')),
                ('completed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('funfam_result', models.TextField()),
                ('funfam_version', models.TextField()),
                ('protein', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='Funfam_residue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_value', models.FloatField()),
                ('funfam_position', models.IntegerField()),
                ('funfam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Funfam')),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Residue')),
            ],
        ),
        migrations.CreateModel(
            name='Flank_residue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amino_acid_type', models.CharField(default='', max_length=1)),
                ('amino_acid_location_n_to_c', models.IntegerField()),
                ('amino_acid_location_in_to_out', models.IntegerField(null=True)),
                ('feature_location', models.TextField(default='Unknown')),
                ('evidence', models.TextField()),
                ('flank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Flank')),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Residue')),
            ],
        ),
        migrations.AddField(
            model_name='flank',
            name='tmh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Tmh'),
        ),
        migrations.CreateModel(
            name='Binding_residue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Residue')),
            ],
        ),
        migrations.CreateModel(
            name='Phmmer_residues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_alignment', models.IntegerField()),
                ('phmmer_alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Phmmer_proteins')),
                ('residue_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residue_database', to='tmh_db.Residue')),
                ('residue_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residue_query', to='tmh_db.Residue')),
            ],
            options={
                'unique_together': {('phmmer_alignment', 'residue_query', 'residue_database')},
            },
        ),
    ]
