# Generated by Django 2.1.7 on 2019-03-21 15:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(max_length=20, unique=True)),
                ('full_sequence', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Residue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amino_acid_type', models.CharField(default='', max_length=1)),
                ('sequence_position', models.IntegerField()),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='Tmh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmh_id', models.TextField(unique=True)),
                ('tmh_sequence', models.TextField()),
                ('tmh_start', models.IntegerField()),
                ('tmh_stop', models.IntegerField()),
                ('tmh_evidence', models.TextField()),
                ('tmh_number', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('membrane_type', models.CharField(default='', max_length=100)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='Tmh_residue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amino_acid_type', models.CharField(default='', max_length=1)),
                ('amino_acid_location', models.IntegerField(default=None)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Residue')),
            ],
        ),
        migrations.CreateModel(
            name='Tmh_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.TextField()),
                ('test_result', models.TextField()),
                ('test_score', models.IntegerField(default=None)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tmh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Tmh')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa_wt', models.CharField(default='', max_length=1)),
                ('aa_mut', models.CharField(default='', max_length=1)),
                ('disease_status', models.TextField()),
                ('disease_comments', models.TextField()),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Residue')),
            ],
        ),
    ]
