# Generated by Django 2.2.3 on 2019-07-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flank',
            name='flank_sequence',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='flank',
            unique_together={('tmh', 'n_or_c')},
        ),
    ]
