# Generated by Django 2.2 on 2019-05-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binding_residue',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
