# Generated by Django 2.1.7 on 2019-03-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmh',
            name='tmh_total_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
