# Generated by Django 2.2.4 on 2019-08-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0002_auto_20190722_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='structural_residue',
            name='porewalker_score',
            field=models.FloatField(null=True),
        ),
    ]
