# Generated by Django 2.2 on 2019-05-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0005_auto_20190515_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='funfam_residue',
            name='funfam_position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pfam_residue',
            name='pfam_position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
