# Generated by Django 2.1.7 on 2019-03-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0005_auto_20190325_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmh_tmsoc',
            name='test_score',
            field=models.FloatField(default=None),
        ),
    ]
