# Generated by Django 2.2.5 on 2019-09-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0005_auto_20190918_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structural_residue',
            name='residue',
        ),
        migrations.AddField(
            model_name='structural_residue',
            name='residue',
            field=models.ManyToManyField(to='tmh_db.Residue'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='pdb_id',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
