# Generated by Django 2.2.5 on 2019-09-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0006_auto_20190918_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='uniprot_protein_id',
            field=models.ManyToManyField(to='tmh_db.Protein'),
        ),
        migrations.AlterUniqueTogether(
            name='structure',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='structure',
            name='uniprot_protein',
        ),
    ]
