# Generated by Django 2.2 on 2019-05-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0006_auto_20190515_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcellular_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(default=None, null=True)),
                ('proteins', models.ManyToManyField(related_name='subcellular_locations', to='tmh_db.Protein')),
            ],
        ),
    ]
