# Generated by Django 2.1.7 on 2019-03-25 17:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0006_auto_20190325_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tmh_deltag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.TextField()),
                ('test_score', models.FloatField(default=None)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tmh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Tmh')),
            ],
        ),
    ]
