# Generated by Django 2.2.5 on 2019-09-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0007_auto_20190923_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='flank_residue',
            name='distance_from_tmh_edge',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
