# Generated by Django 2.2 on 2019-06-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0007_subcellular_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniref',
            name='protein',
        ),
        migrations.AddField(
            model_name='uniref',
            name='protein',
            field=models.ManyToManyField(to='tmh_db.Protein'),
        ),
    ]
