# Generated by Django 2.1.7 on 2019-03-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0008_tmh_hydrophobicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmh_hydrophobicity',
            name='aromaticity',
            field=models.FloatField(default=None),
        ),
    ]
