# Generated by Django 2.2 on 2019-06-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0008_auto_20190603_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uniref',
            old_name='representitive_id',
            new_name='representative_id',
        ),
    ]
