# Generated by Django 2.2.5 on 2019-10-08 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0008_flank_residue_distance_from_tmh_edge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Non_tmh_helix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helix_start', models.IntegerField()),
                ('helix_stop', models.IntegerField()),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='Non_tmh_helix_residue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amino_acid_type', models.CharField(default='', max_length=1)),
                ('nont_tmh_helix_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Non_tmh_helix')),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Residue')),
            ],
        ),
    ]
