# Generated by Django 2.2 on 2019-06-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0009_auto_20190603_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uniref',
            old_name='protein',
            new_name='proteins',
        ),
    ]
