# Generated by Django 2.2.5 on 2019-10-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0009_non_tmh_helix_non_tmh_helix_residue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flank_residue',
            name='distance_from_tmh_edge',
        ),
    ]
