# Generated by Django 2.1.7 on 2019-03-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0009_tmh_hydrophobicity_aromaticity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='residue',
            unique_together={('protein', 'sequence_position')},
        ),
    ]
