# Generated by Django 2.2 on 2019-06-03 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0010_auto_20190603_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phmmer_proteins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_e_value', models.FloatField(null=True)),
                ('domain_e_value', models.FloatField(null=True)),
                ('protein_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein_database_uniprot_id', to='tmh_db.Protein')),
                ('protein_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein_query_uniprot_id', to='tmh_db.Protein')),
            ],
            options={
                'unique_together': {('protein_query', 'protein_database')},
            },
        ),
        migrations.CreateModel(
            name='Phmmer_residues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_alignment', models.IntegerField()),
                ('phmmer_alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Phmmer_proteins')),
                ('residue_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residue_database', to='tmh_db.Residue')),
                ('residue_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residue_query', to='tmh_db.Residue')),
            ],
            options={
                'unique_together': {('phmmer_alignment', 'residue_query', 'residue_database')},
            },
        ),
    ]
