# Generated by Django 2.2.5 on 2019-12-06 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0010_remove_flank_residue_distance_from_tmh_edge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal_peptide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_sequence', models.TextField()),
                ('signal_start', models.IntegerField()),
                ('signal_stop', models.IntegerField()),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='Signal_residue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amino_acid_type', models.CharField(default='', max_length=1)),
                ('amino_acid_location_n_to_c', models.IntegerField()),
                ('amino_acid_location_in_to_out', models.IntegerField(null=True)),
                ('feature_location', models.TextField(default='Unknown')),
                ('evidence', models.TextField()),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Residue')),
                ('the_signal_peptide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Signal_peptide')),
            ],
        ),
    ]
