# Generated by Django 2.1.7 on 2019-03-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0010_auto_20190326_1138'),
    ]

    #operations = [
    #    migrations.AddField(
    #        model_name='tmh_hydrophobicity',
    #        name='flexibility',
    #        field=models.FloatField(default=None),
    #    ),
    ##    migrations.AddField(
    ##        model_name='variant',
    ##        name='variant_source',
    ##        field=models.TextField(default=''),
    ##        preserve_default=False,
    ##    ),
    ##]
