# Generated by Django 2.1.7 on 2019-03-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0011_auto_20190326_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmh',
            name='tmh_total_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='variant',
            name='variant_source',
            field=models.TextField(default='Unknown'),
        ),
    ]
