# Generated by Django 2.2.2 on 2019-06-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0011_phmmer_proteins_phmmer_residues'),
    ]

    operations = [
        migrations.AddField(
            model_name='structural_residue',
            name='memprotmd_headgroups',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='structural_residue',
            name='memprotmd_tail',
            field=models.FloatField(null=True),
        ),
    ]
