# Generated by Django 2.2.5 on 2019-12-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0011_signal_peptide_signal_residue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal_residue',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='signal_residue',
            name='feature_location',
        ),
    ]
