# Generated by Django 2.1.7 on 2019-03-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0012_auto_20190326_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmh_hydrophobicity',
            name='flexibility',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='variant_source',
            field=models.TextField(default='Unknown'),
        ),
    ]
