# Generated by Django 2.2.5 on 2019-12-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0012_auto_20191206_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal_residue',
            name='amino_acid_location_in_to_out',
        ),
        migrations.RemoveField(
            model_name='signal_residue',
            name='amino_acid_location_n_to_c',
        ),
    ]
