# Generated by Django 2.2.5 on 2019-12-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0013_auto_20191206_1557'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='structural_residue',
            unique_together={('structure', 'pdb_position', 'pdb_chain')},
        ),
    ]
