# Generated by Django 2.2.5 on 2019-12-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0014_auto_20191210_1555'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phmmer_residues',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='phmmer_residues',
            name='phmmer_alignment',
        ),
        migrations.RemoveField(
            model_name='phmmer_residues',
            name='residue_database',
        ),
        migrations.RemoveField(
            model_name='phmmer_residues',
            name='residue_query',
        ),
        migrations.DeleteModel(
            name='Phmmer_proteins',
        ),
        migrations.DeleteModel(
            name='Phmmer_residues',
        ),
    ]
