# Generated by Django 2.2.5 on 2019-12-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0015_auto_20191217_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pfam_residue',
            name='pfam',
        ),
        migrations.RemoveField(
            model_name='pfam_residue',
            name='residue',
        ),
        migrations.RemoveField(
            model_name='tail_anchor',
            name='protein',
        ),
        migrations.AddField(
            model_name='protein',
            name='tail_anchor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='protein',
            name='tail_anchor_evidence',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='residue',
            name='binding_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='residue',
            name='binding_residue',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Binding_residue',
        ),
        migrations.DeleteModel(
            name='Pfam',
        ),
        migrations.DeleteModel(
            name='Pfam_residue',
        ),
        migrations.DeleteModel(
            name='Tail_anchor',
        ),
    ]
