# Generated by Django 2.2.5 on 2019-12-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0017_auto_20191218_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniref',
            name='representative_uniprot_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='uniref',
            name='representative_uniref_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
