# Generated by Django 2.2.5 on 2020-01-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0018_auto_20191218_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmh',
            name='meta_tmh',
            field=models.BooleanField(null=True),
        ),
    ]
