# Generated by Django 2.2 on 2019-04-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0018_protein_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='variant_source_id',
            field=models.TextField(default='No_ID'),
        ),
    ]
