# Generated by Django 2.2 on 2019-04-10 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0019_variant_variant_source_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmh_residue',
            old_name='protein',
            new_name='residue',
        ),
        migrations.CreateModel(
            name='Funfam_residue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funfam_id', models.TextField()),
                ('e_value', models.FloatField()),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Residue')),
            ],
        ),
    ]
