# Generated by Django 3.0.4 on 2020-04-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0020_variant_variant_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='structural_residue',
            name='pore_residue',
            field=models.BooleanField(default=False),
        ),
    ]
