# Generated by Django 2.2 on 2019-04-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0021_funfamstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='funfamstatus',
            name='funfam',
            field=models.TextField(default='Funfam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funfamstatus',
            name='submission_key',
            field=models.TextField(default='NA'),
        ),
    ]
