# Generated by Django 3.0.4 on 2020-04-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0021_structural_residue_pore_residue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structural_residue',
            name='porewalker_score',
        ),
    ]
