# Generated by Django 3.0.4 on 2020-05-21 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0022_remove_structural_residue_porewalker_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='funfam',
            name='uniprot_protein',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Protein'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funfam_residue',
            name='funfam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Protein'),
        ),
        migrations.DeleteModel(
            name='Funfamstatus',
        ),
    ]
