# Generated by Django 2.2 on 2019-04-10 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0023_auto_20190410_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funfamstatus',
            name='protein',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Protein'),
        ),
    ]
