# Generated by Django 2.2 on 2019-04-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0024_auto_20190410_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funfamstatus',
            old_name='funfam',
            new_name='funfam_version',
        ),
    ]
