# Generated by Django 3.0.4 on 2020-06-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0024_auto_20200611_1547'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='funfam_residue',
            unique_together={('funfam', 'funfam_position')},
        ),
    ]
