# Generated by Django 2.2 on 2019-04-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0025_auto_20190411_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmh_residue',
            name='evidence',
            field=models.TextField(default='UniProt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tmh_residue',
            name='feature_location',
            field=models.TextField(default='TMH'),
            preserve_default=False,
        ),
    ]
