# Generated by Django 2.2 on 2019-04-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0026_auto_20190424_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='total_tmh_number',
            field=models.IntegerField(default=0),
        ),
    ]
