# Generated by Django 2.2.5 on 2020-07-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0026_auto_20200617_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.TextField(unique=True)),
                ('implicated_variants', models.ManyToManyField(to='tmh_db.Variant')),
            ],
        ),
    ]
