# Generated by Django 2.2.5 on 2020-07-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0027_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='germline',
            field=models.BooleanField(null=True),
        ),
    ]
