# Generated by Django 2.2 on 2019-04-24 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0027_protein_total_tmh_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmh_residue',
            name='tmh_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Tmh'),
            preserve_default=False,
        ),
    ]
