# Generated by Django 3.1.1 on 2020-11-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0028_variant_germline'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='maf',
            field=models.FloatField(default=None, null=True),
        ),
    ]
