# Generated by Django 3.1.1 on 2020-11-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0029_variant_maf'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='qc',
            field=models.TextField(default=None, null=True),
        ),
    ]
