# Generated by Django 3.1.1 on 2020-11-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0030_variant_qc'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='mis_z_gn',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='protein',
            name='oe_lof_upper_gn',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='protein',
            name='oe_mis_upper_gn',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='protein',
            name='pLI_gn',
            field=models.FloatField(default=None, null=True),
        ),
    ]
