# Generated by Django 2.2 on 2019-04-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0030_auto_20190425_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmh_residue',
            name='amino_acid_location_in_to_out',
            field=models.IntegerField(null=True),
        ),
    ]
