# Generated by Django 2.2 on 2019-04-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0031_auto_20190425_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Go',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go_id', models.CharField(max_length=20, unique=True)),
                ('proteins', models.ManyToManyField(related_name='gos', to='tmh_db.Protein')),
            ],
        ),
    ]
