# Generated by Django 2.2 on 2019-04-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0032_go'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(unique=True)),
                ('proteins', models.ManyToManyField(related_name='keywords', to='tmh_db.Protein')),
            ],
        ),
    ]
