# Generated by Django 2.2 on 2019-05-02 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0033_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_id', models.CharField(default='', max_length=10)),
                ('uniprot_protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='Structural_residue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_position', models.IntegerField()),
                ('author_position', models.IntegerField()),
                ('uniprot_position', models.IntegerField()),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Residue')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Structure')),
            ],
        ),
    ]
