# Generated by Django 3.1.5 on 2021-04-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0034_auto_20210413_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structural_residue',
            old_name='memprotmd_headgroups',
            new_name='memprotmd_head',
        ),
    ]
