# Generated by Django 2.2 on 2019-05-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0035_binding_residue'),
    ]

    operations = [
        migrations.AddField(
            model_name='structural_residue',
            name='pdb_chain',
            field=models.CharField(default='', max_length=10),
        ),
    ]
