# Generated by Django 2.2 on 2019-05-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0036_structural_residue_pdb_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='database_metadata',
            name='build',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database_metadata',
            name='version',
            field=models.TextField(default='dev'),
            preserve_default=False,
        ),
    ]
