# Generated by Django 2.2 on 2019-05-08 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0037_auto_20190507_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uniref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representitive_id', models.CharField(max_length=20, unique=True)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmh_db.Protein')),
            ],
        ),
    ]
