# Generated by Django 2.2 on 2019-05-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0038_uniref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structural_residue',
            name='author_position',
            field=models.IntegerField(null=True),
        ),
    ]
