# Generated by Django 2.2 on 2019-05-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmh_db', '0040_structural_residue_structure_aa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structural_residue',
            name='structure_aa',
            field=models.CharField(default='X', max_length=1, null=True),
        ),
    ]
